#!/bin/sh

usage() {
	echo "getmac <wl3 | wl2 | wl1 | wl0 | lan | wan | eth0 | eth1 | eth2 | eth3 | eth4 *>"
	echo "example: getmac"
	echo "         getmac wan|eth4"
	echo "         getmac lan|eth1"
	echo "         getmac eth2"
	echo "         getmac eth3"
	echo "         getmac wl0"
	echo "         getmac wl1"
	echo "         getmac wl2"
	echo "         getmac wl3"
}

art_mtd=`cat /proc/mtd | grep ART | cut -d ":" -f 1`
[ -z "$art_mtd" ] && exit 1

get_eth0()
{
	eth0adr="`hexdump -s 0 -n 6 -e '6/1 "%02x:"'  /dev/"$art_mtd" | cut -b-17`"
}

get_eth1()
{
	eth1adr="`hexdump -s 6 -n 6 -e '6/1 "%02x:"'  /dev/"$art_mtd" | cut -b-17`"
}

get_eth2()
{
	eth2adr="`hexdump -s 12 -n 6 -e '6/1 "%02x:"'  /dev/"$art_mtd" | cut -b-17`"
}

get_eth3()
{
	eth3adr="`hexdump -s 18 -n 6 -e '6/1 "%02x:"'  /dev/"$art_mtd" | cut -b-17`"
}

get_eth4()
{
	eth4adr="`hexdump -s 24 -n 6 -e '6/1 "%02x:"'  /dev/"$art_mtd" | cut -b-17`"
}

#wifi0 wifi1都是soc0的子设备，用caldata.bin
get_wifi0()
{
	wifi0adr="`hexdump -s 14 -n 6 -e '6/1 "%02x:"' /tmp/IPQ8074/caldata.bin | cut -b -17`"
	[ "${wifi0adr}" == "" -o "$wifi0adr" = "ff:ff:ff:ff:ff:ff" ] && wifi0adr="`cat /sys/class/net/wifi0/address 2>/dev/null`"
	ath0adr="$wifi0adr"
}

get_wifi1()
{
	wifi1adr="`hexdump -s 20 -n 6 -e '6/1 "%02x:"' /tmp/IPQ8074/caldata.bin -e | cut -b -17`"
	[ "${wifi1adr}" == "" -o "$wifi1adr" = "ff:ff:ff:ff:ff:ff" ] && wifi1adr="`cat /sys/class/net/wifi1/address 2>/dev/null`"
	ath1adr="$wifi1adr"
}

get_wifi2()
{
	wifi2adr="`hexdump -s 14 -n 6 -e '6/1 "%02x:"' /tmp/qcn9000/caldata_1.bin | cut -b -17`"
	[ "${wifi2adr}" == "" -o "$wifi2adr" = "ff:ff:ff:ff:ff:ff" ] && wifi2adr="`cat /sys/class/net/wifi2/address 2>/dev/null`"
	ath2adr="$wifi2adr"
}

get_wifi3()
{
	wifi3adr="`hexdump -s 6 -n 6 -e '6/1 "%02x:"' /tmp/wifi2.caldata  -e | cut -b -17`"
	[ "${wifi3adr}" == "" -o "$wifi3adr" = "ff:ff:ff:ff:ff:ff" ] && wifi1adr="`cat /sys/class/net/wifi3/address 2>/dev/null`"
	ath3adr="$wifi3adr"
}

# eth0 eth1 2g 5g eth2 eth3 bt
case $1 in
	-h)
	usage
	;;

	wl0|wifi0)
	# wl0=5g iface, to adapt miwifi habit
	get_wifi0
	echo "$ath0adr"
	;;
	
	wl1|wifi1)
	# wl1=2.4g iface, to adapt miwifi habit
	get_wifi1
	echo "$ath1adr"
	;;

	wl2|wifi2)
	get_wifi2
	echo "$ath2adr"
	;;

	wl3|wifi3)
	get_wifi3
	echo "$ath3adr"
	;;

	lan|eth0|eth1|eth2|eth3)
	get_eth1
	echo "$eth1adr"
	;;

	wan|eth4|eth5)
	get_eth4
	echo "$eth4adr"
	;;

	*)
	get_eth4
	get_eth1
	get_wifi0
	get_wifi1
	get_wifi2
	get_wifi3
	if [ "$wifi1adr" = "ff:ff:ff:ff:ff:ff" -o "$wifi2adr" = "ff:ff:ff:ff:ff:ff" ]; then
		# assume no wl0 5G adapter
		echo "$eth4adr,$ath0adr,$ath1adr"
	else
		echo "$eth4adr,$eth1adr,$ath0adr,$ath1adr,$ath2adr,$ath3adr"
	fi
	;;
esac

