#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1
NAME=meshd
BHTAG="game"
PROG=/usr/sbin/meshd

start_service() {
	local init_flag=$(uci -q get xiaoqiang.common.INITTED)
	local bh_tag="$BHTAG"
	local device=$(uci -q get misc.wireless.if_${bh_tag})
	local mac=$(uci -q get wireless.$device.macaddr)
	local ifname=$(uci -q get misc.wireless.ifname_${bh_tag})
	if [ "$init_flag" != "YES" ]; then
		procd_open_instance
		procd_set_param command "$PROG" -i $ifname -t 10 -a $mac
		procd_set_param respawn
		procd_close_instance
	fi
}
