#!/bin/sh

# EMC2301, connected to GSBI1 I2C
HWMON_SYSFS_EMC2301=/sys/devices/platform/soc/78ba000.i2c/i2c-1/1-002f
HWMON_SYSFS_LM63=/sys/devices/platform/soc/78ba000.i2c/i2c-1/1-004c/hwmon/hwmon0
MAXRPM=2500

if [ "$#" -ne 1 ]; then
	echo "error param" >&2
	exit 255
fi

if [ -d $HWMON_SYSFS_EMC2301/hwmon ]; then
	#echo "USE EMC2301" >&2
	HWMON_SYSFS=$HWMON_SYSFS_EMC2301
elif [ -d $HWMON_SYSFS_LM63 ]; then
	#echo "USE LM63" >&2
	HWMON_SYSFS=$HWMON_SYSFS_LM63
else
	echo "Fan controller is not present." >&2
	exit 1
fi

case $1 in
	[0-9]*)
		if [ $1 -gt 20 ]; then
			echo "fan cycle 0-20" >&2
			exit 255
		fi
		;;
	*)
		echo "fan cycle 0-20" >&2
		exit 255
		;;
esac
duty5p=$1
echo 1 > $HWMON_SYSFS/pwm1_enable
echo $((255 * duty5p / 20)) > $HWMON_SYSFS/pwm1
echo "fan cycle - $((duty5p * MAXRPM / 20))" >&2
