#!/bin/sh /etc/rc.common

START=55
STOP=55

USE_PROCD=1
PROG=/opt/filetunnel/stunserver


start_service() {
	procd_open_instance
	procd_set_param command "$PROG" --verbosity 1
	procd_set_param respawn
	procd_close_instance
}
