#!/bin/sh

if [ $# -eq 0 ]; then
	echo "wps [commands] [parameters]"
	echo "	pbc"
	echo "	status"
	echo "	stamac"
	echo "	stop"
	return
fi

WLANCONFIG=/usr/sbin/wlanconfig
TIMETHR=60
WPS_FILE_5G=/tmp/wpswl0
WPS_FILE_2G=/tmp/wpswl1
WPS_FILE_GAME=/tmp/wpswl2
is5g=0
is2g=0
isgame=0
ifname2g="`uci get misc.wireless.ifname_2G`"
ifname5g="`uci get misc.wireless.ifname_5G`"
ifnamegame="`uci get misc.wireless.ifname_game`"
device2g="`uci get misc.wireless.if_2G`"
device5g="`uci get misc.wireless.if_5G`"
devicegame="`uci get misc.wireless.if_game`"
new_sta_onre_f="/tmp/new_sta_onre"

cat /proc/net/dev | grep -w "${ifname5g}" > /dev/null 2>&1
[ $? -eq 0 ] && is5g=1
cat /proc/net/dev | grep -w "${ifname2g}" > /dev/null 2>&1
[ $? -eq 0 ] && is2g=1
cat /proc/net/dev | grep -w "${ifnamegame}" > /dev/null 2>&1
[ $? -eq 0 ] && isgame=1

check_sta_online()
{
	stamac=$1
	ifname=$2
	if [ -z "${stamac}" ] || [ -z "${ifname}" ]; then
		return 0
	fi
	${WLANCONFIG} "${ifname}" list | grep "${stamac}" > /dev/null
	if [ $? -eq 0 ]; then
		onlinetimestr="`${WLANCONFIG} "${ifname}" list | awk -F ' ' '{if($1==sta){print $20}}' sta=${stamac}`"
		if [ -n "${onlinetimestr}" ]; then
			hour="`echo "${onlinetimestr}" | awk -F ':' '{print$1}'`"
			min="`echo "${onlinetimestr}" | awk -F ':' '{print$2}'`"
			sec="`echo "${onlinetimestr}" | awk -F ':' '{print$3}'`"
			onlinetime=$((hour*3600+min*60+sec))
			[ ${onlinetime} -lt ${TIMETHR} ] && return 1
		fi
	else
		return 2
	fi
	return 0
}

case $1 in
	"pbc")
		rm -rf ${new_sta_onre_f} 2>/dev/null
		[ ${is5g} -eq 1 ] && hostapd_cli -i "${ifname5g}" -p /var/run/hostapd-${device5g}/ wps_pbc && echo 1 > ${WPS_FILE_5G}
		[ ${is2g} -eq 1 ] && hostapd_cli -i "${ifname2g}" -p /var/run/hostapd-${device2g}/ wps_pbc && echo 1 > ${WPS_FILE_2G}
		[ ${isgame} -eq 1 ] && hostapd_cli -i "${ifnamegame}" -p /var/run/hostapd-${devicegame}/ wps_pbc && echo 1 > ${WPS_FILE_GAME}
		;;
	"status")
		#return 0:close 1:start 2:connect 3:error 4:timeout
		status=0
		status5=100
		status2=100
		statusgame=100
		if [ ${is5g} -eq 1 ]; then
			status5=0
			wpsstatus5="`hostapd_cli -i "${ifname5g}" -p /var/run/hostapd-${device5g}/ wps_get_status`"
			statusstr5="`echo "${wpsstatus5}" | awk -F ' ' '/Status/{print$3}'`"
			if [ "Disabled" = "${statusstr5}" ]; then
				resultstr5="`echo "${wpsstatus5}" | awk -F ' ' '/Last WPS result/{print$4}'`"
				if [ "Success" = "${resultstr5}" ]; then
					stamac="`echo "${wpsstatus5}" | awk -F ' ' '/Peer Address/{print$3}'`"
					if [ -n ${stamac} ]; then
						check_sta_online ${stamac} ${ifname5g}
						ret=$?
						if [ ${ret} -eq 1 ]; then
							status5=2
							echo 2 > ${WPS_FILE_5G}
						elif [ ${ret} -eq 2 ]; then
							check_sta_online ${stamac} ${ifname2g}
							ret=$?
							if [ ${ret} -eq 1 ]; then
								status5=2
								echo 2 > ${WPS_FILE_5G}
							elif [ ${ret} -eq 2 ]; then
								check_sta_online ${stamac} ${ifnamegame}
								ret=$?
								if [ ${ret} -eq 1 ]; then
									status5=2
									echo 2 > ${WPS_FILE_5G}
								fi
							fi
						fi
					fi
				fi
				if [ -f ${WPS_FILE_5G} ] && [ "`cat ${WPS_FILE_5G}`" = "1" ] && [ ${status5} -eq 0 ]; then
					status5=1
				fi
			elif [ "Active" = "${statusstr5}" ]; then
				status5=1
			elif [ "Timed-out" = "${statusstr5}" ]; then
				status5=4
			fi
		fi

		if [ ${is2g} -eq 1 ]; then
			status2=0
			wpsstatus2="`hostapd_cli -i "${ifname2g}" -p /var/run/hostapd-${device2g}/ wps_get_status`"
			statusstr2="`echo "${wpsstatus2}" | awk -F ' ' '/Status/{print$3}'`"
			if [ "Disabled" = "${statusstr2}" ]; then
				resultstr2="`echo "${wpsstatus2}" | awk -F ' ' '/Last WPS result/{print$4}'`"
				if [ "Success" = "${resultstr2}" ]; then
					stamac="`echo "${wpsstatus2}" | awk -F ' ' '/Peer Address/{print$3}'`"
					if [ -n ${stamac} ]; then
						check_sta_online ${stamac} ${ifname2g}
						ret=$?
						if [ ${ret} -eq 1 ]; then
							status2=2
							echo 2 > ${WPS_FILE_2G}
						elif [ ${ret} -eq 2 ]; then
							check_sta_online ${stamac} ${ifname5g}
							ret=$?
							if [ ${ret} -eq 1 ]; then
								status2=2
								echo 2 > ${WPS_FILE_2G}
							elif [ ${ret} -eq 2 ]; then
								check_sta_online ${stamac} ${ifnamegame}
								ret=$?
								if [ ${ret} -eq 1 ]; then
									status2=2
									echo 2 > ${WPS_FILE_2G}
								fi
							fi
						fi
					fi
				fi
				if [ -f ${WPS_FILE_2G} ] && [ "`cat ${WPS_FILE_2G}`" = "1" ] && [ ${status2} -eq 0 ]; then
					status2=1
				fi
			elif [ "Active" = "${statusstr2}" ]; then
				status2=1
			elif [ "Timed-out" = "${statusstr2}" ]; then
				status2=4
			fi
		fi

		if [ ${isgame} -eq 1 ]; then
			statusgame=0
			wpsstatusgame="`hostapd_cli -i "${ifnamegame}" -p /var/run/hostapd-${devicegame}/ wps_get_status`"
			statusstrgame="`echo "${wpsstatusgame}" | awk -F ' ' '/Status/{print$3}'`"
			if [ "Disabled" = "${statusstrgame}" ]; then
				resultstrgame="`echo "${wpsstatusgame}" | awk -F ' ' '/Last WPS result/{print$4}'`"
				if [ "Success" = "${resultstrgame}" ]; then
					stamac="`echo "${wpsstatusgame}" | awk -F ' ' '/Peer Address/{print$3}'`"
					if [ -n ${stamac} ]; then
						check_sta_online ${stamac} ${ifnamegame}
						ret=$?
						if [ ${ret} -eq 1 ]; then
							statusgame=2
							echo 2 > ${WPS_FILE_GAME}
						elif [ ${ret} -eq 2 ]; then
							check_sta_online ${stamac} ${ifname5g}
							ret=$?
							if [ ${ret} -eq 1 ]; then
								statusgame=2
								echo 2 > ${WPS_FILE_GAME}
							elif [ ${ret} -eq 2 ]; then
								check_sta_online ${stamac} ${ifname2g}
								ret=$?
								if [ ${ret} -eq 1 ]; then
									statusgame=2
									echo 2 > ${WPS_FILE_GAME}
								fi
							fi
						fi
					fi
				fi
				if [ -f ${WPS_FILE_GAME} ] && [ "`cat ${WPS_FILE_GAME}`" = "1" ] && [ ${statusgame} -eq 0 ]; then
					statusgame=1
				fi
			elif [ "Active" = "${statusstrgame}" ]; then
				statusgame=1
			elif [ "Timed-out" = "${statusstrgame}" ]; then
				statusgame=4
			fi
		fi

		if [ "${status5}" -eq 4 ] || [ "${status2}" -eq 4 ] || [ "${statusgame}" -eq 4 ]; then
			status=4
			rm -rf ${WPS_FILE_5G} ${WPS_FILE_2G} ${WPS_FILE_GAME} > /dev/null 2>&1
		elif [ "${status5}" -eq 0 ] || [ "${status2}" -eq 0 ] || [ "${statusgame}" -eq 0 ]; then
			status=0
			rm -rf ${WPS_FILE_5G} ${WPS_FILE_2G} ${WPS_FILE_GAME} > /dev/null 2>&1
		elif [ "${status5}" -eq 2 ] || [ "${status2}" -eq 2 ] || [ "${statusgame}" -eq 2 ]; then
			status=2
		elif [ "${status5}" -eq 1 ] || [ "${status2}" -eq 1 ] || [ "${statusgame}" -eq 1 ]; then
			status=1
		fi

		# wps also done if new sta online on re
		if [ "${status}" -eq 1 ] && [ -f "${new_sta_onre_f}" ] && [ -n "`cat ${new_sta_onre_f}`" ]; then
			status=2
		fi
		echo ${status}
		;;
	"stamac")
		#return 0:close 1:start 2:connect 3:error 4:timeout
		status=0
		status5=100
		status2=100
		statusgame=100
		if [ ${is5g} -eq 1 ]; then
			status5=0
			wpsstatus5="`hostapd_cli -i "${ifname5g}" -p /var/run/hostapd-${device5g}/ wps_get_status`"
			statusstr5="`echo "${wpsstatus5}" | awk -F ' ' '/Status/{print$3}'`"
			if [ "Disabled" = "${statusstr5}" ]; then
				resultstr5="`echo "${wpsstatus5}" | awk -F ' ' '/Last WPS result/{print$4}'`"
				if [ "Success" = "${resultstr5}" ]; then
					stamac5="`echo "${wpsstatus5}" | awk -F ' ' '/Peer Address/{print$3}'`"
					if [ -n ${stamac5} ]; then
						check_sta_online ${stamac5} ${ifname5g}
						ret=$?
						if [ ${ret} -eq 1 ]; then
							status5=2
						elif [ ${ret} -eq 2 ]; then
							check_sta_online ${stamac5} ${ifname2g}
							ret=$?
							if [ ${ret} -eq 1 ]; then
								status5=2
							elif [ ${ret} -eq 2 ]; then
								check_sta_online ${stamac5} ${ifnamegame}
								ret=$?
								if [ ${ret} -eq 1 ]; then
									status5=2
								fi
							fi
						fi
					fi
				fi
			elif [ "Active" = "${statusstr5}" ]; then
				status5=1
			elif [ "Timed-out" = "${statusstr5}" ]; then
				status5=4
			fi
		fi

		if [ ${is2g} -eq 1 ]; then
			status2=0
			wpsstatus2="`hostapd_cli -i "${ifname2g}" -p /var/run/hostapd-${device2g}/ wps_get_status`"
			statusstr2="`echo "${wpsstatus2}" | awk -F ' ' '/Status/{print$3}'`"
			if [ "Disabled" = "${statusstr2}" ]; then
				resultstr2="`echo "${wpsstatus2}" | awk -F ' ' '/Last WPS result/{print$4}'`"
				if [ "Success" = "${resultstr2}" ]; then
					stamac2="`echo "${wpsstatus2}" | awk -F ' ' '/Peer Address/{print$3}'`"
					if [ -n ${stamac2} ]; then
						check_sta_online ${stamac2} ${ifname2g}
						ret=$?
						if [ ${ret} -eq 1 ]; then
							status2=2
						elif [ ${ret} -eq 2 ]; then
							check_sta_online ${stamac2} ${ifname5g}
							ret=$?
							if [ ${ret} -eq 1 ]; then
								status2=2
							elif [ ${ret} -eq 2 ]; then
								check_sta_online ${stamac2} ${ifnamegame}
								ret=$?
								if [ ${ret} -eq 1 ]; then
									status2=2
								fi
							fi
						fi
					fi
				fi
			elif [ "Active" = "${statusstr2}" ]; then
				status2=1
			elif [ "Timed-out" = "${statusstr2}" ]; then
				status2=4
			fi
		fi

		if [ ${isgame} -eq 1 ]; then
			statusgame=0
			wpsstatusgame="`hostapd_cli -i "${ifnamegame}" -p /var/run/hostapd-${devicegame}/ wps_get_status`"
			statusstrgame="`echo "${wpsstatusgame}" | awk -F ' ' '/Status/{print$3}'`"
			if [ "Disabled" = "${statusstrgame}" ]; then
				resultstrgame="`echo "${wpsstatusgame}" | awk -F ' ' '/Last WPS result/{print$4}'`"
				if [ "Success" = "${resultstrgame}" ]; then
					stamacgame="`echo "${wpsstatusgame}" | awk -F ' ' '/Peer Address/{print$3}'`"
					if [ -n ${stamacgame} ]; then
						check_sta_online ${stamacgame} ${ifnamegame}
						ret=$?
						if [ ${ret} -eq 1 ]; then
							statusgame=2
						elif [ ${ret} -eq 2 ]; then
							check_sta_online ${stamacgame} ${ifname5g}
							ret=$?
							if [ ${ret} -eq 1 ]; then
								statusgame=2
								elif [ ${ret} -eq 2 ]; then
								check_sta_online ${stamacgame} ${ifname2g}
								ret=$?
								if [ ${ret} -eq 1 ]; then
									statusgame=2
								fi
							fi
						fi
					fi
				fi
			elif [ "Active" = "${statusstrgame}" ]; then
				statusgame=1
			elif [ "Timed-out" = "${statusstrgame}" ]; then
				statusgame=4
			fi
		fi

		if [ "${status5}" -eq 4 ] || [ "${status2}" -eq 4 ] || [ "${statusgame}" -eq 4 ]; then
			status=4
		elif [ "${status5}" -eq 0 ] || [ "${status2}" -eq 0 ] || [ "${statusgame}" -eq 0 ]; then
			status=0
		elif [ "${status5}" -eq 2 ] || [ "${status2}" -eq 2 ] || [ "${statusgame}" -eq 2 ]; then
			status=2
			if [ "${status5}" -eq 2 ]; then
				stamac="${stamac5}"
			elif [ "${status2}" -eq 2 ]; then
				stamac="${stamac2}"
			elif [ "${statusgame}" -eq 2 ]; then
				stamac="${stamacgame}"
			fi
		fi
		# wps also done if new sta online on re
		if [ -z "${stamac}" ] && [ -f "${new_sta_onre_f}" ] && [ -n "`cat ${new_sta_onre_f}`" ]; then
			stamac="`cat "${new_sta_onre_f}"`"
		fi
		echo ${stamac}
		;;
	"stop")
		rm -rf ${new_sta_onre_f} 2>/dev/null
		[ ${is5g} -eq 1 ] && hostapd_cli -i "${ifname5g}" -p /var/run/hostapd-${device5g}/ wps_cancel && rm -rf ${WPS_FILE_5G}
		[ ${is2g} -eq 1 ] && hostapd_cli -i "${ifname2g}" -p /var/run/hostapd-${device2g}/ wps_cancel && rm -rf ${WPS_FILE_2G}
		[ ${isgame} -eq 1 ] && hostapd_cli -i "${ifnamegame}" -p /var/run/hostapd-${devicegame}/ wps_cancel && rm -rf ${WPS_FILE_GAME}
		;;
	*) echo "Parameter $1 is not supported";;
esac
